$axure.loadCurrentPage({
  "url":"求救设置.html",
  "generationDate":new Date(1429966253570.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8aa30889eaa4f96af368ae6d25e2619",
    "type":"Axure:Page",
    "name":"求救设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0c3b5afee55e4df5b124246efd61cfba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":240,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b31c7befce9744d19e578967c2bebfd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":240,
                  "height":477}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u0.png"}},
{
          "id":"269dff1e2e1343c385f94d1c5d465096",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"b51aca3f31b84f65b22a1e4028c30776",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcbb99a8dd6b4e519e08e1d7382abce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"02ec8990d68a490dadafe994cb360961",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":230},
            "size":{
              "width":314,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031cc39982af4c8dbacfce11d696f004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":230},
                "size":{
                  "width":314,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救设置/u10.png"}},
{
          "id":"5639ef165c9841e7904f3917e1e41490",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":310},
            "size":{
              "width":314,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64821236a7c74463969cd02247ccf8a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":310},
                "size":{
                  "width":314,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救设置/u10.png"}},
{
          "id":"2f3d5936787c444daa0a9aae93e18180",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":320},
            "size":{
              "width":106,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aad7d3285c84236b5b3ac11cfc80c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":320},
                "size":{
                  "width":106,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救设置/u14.png"}},
{
          "id":"064c2733da454d76bd32bcb5f2646648",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":240},
            "size":{
              "width":99,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51feb3b4da9843b496d2710dd3402507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":240},
                "size":{
                  "width":99,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救设置/u16.png"}},
{
          "id":"9861ee04aa4544b481ea5aff0ded5abe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":110},
            "size":{
              "width":43,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c68a41c1e5d43e7b57f028cfce178ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":110},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救设置/u18.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "0c3b5afee55e4df5b124246efd61cfba":{
      "scriptId":"u0"},
    "b31c7befce9744d19e578967c2bebfd6":{
      "scriptId":"u1"},
    "269dff1e2e1343c385f94d1c5d465096":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "b51aca3f31b84f65b22a1e4028c30776":{
      "scriptId":"u8"},
    "bcbb99a8dd6b4e519e08e1d7382abce3":{
      "scriptId":"u9"},
    "02ec8990d68a490dadafe994cb360961":{
      "scriptId":"u10"},
    "031cc39982af4c8dbacfce11d696f004":{
      "scriptId":"u11"},
    "5639ef165c9841e7904f3917e1e41490":{
      "scriptId":"u12"},
    "64821236a7c74463969cd02247ccf8a9":{
      "scriptId":"u13"},
    "2f3d5936787c444daa0a9aae93e18180":{
      "scriptId":"u14"},
    "0aad7d3285c84236b5b3ac11cfc80c26":{
      "scriptId":"u15"},
    "064c2733da454d76bd32bcb5f2646648":{
      "scriptId":"u16"},
    "51feb3b4da9843b496d2710dd3402507":{
      "scriptId":"u17"},
    "9861ee04aa4544b481ea5aff0ded5abe":{
      "scriptId":"u18"},
    "3c68a41c1e5d43e7b57f028cfce178ac":{
      "scriptId":"u19"}}});