$axure.loadCurrentPage({
  "url":"设备绑定.html",
  "generationDate":new Date(1429966254368.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c2802f7d92a46d691257aa914f9da5a",
    "type":"Axure:Page",
    "name":"设备绑定",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ea4f7bb220cd4bbb81ab930bc80242df",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"9906bcc370bf455e91ae86e15ded411d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":112},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39af8eb78b01490985e6596ea5ba1cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":112},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号注册/u8.png"}},
{
          "id":"becddf3ac5994c50afdc664c08ffbbe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":152},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e10ea809c4a4a77adec50997fbf8cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":152},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号注册/u8.png"}},
{
          "id":"659f2c4a690e48588c338b6afc76cbb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":191},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62531fa630fa4b0fb5ebe7a2e4fdc166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":191},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号注册/u8.png"}},
{
          "id":"cb3e98e9f38e466ab3d6e04214c9fe91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":307,
              "y":112},
            "size":{
              "width":80,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63e65217bc564b4a94d0da9342be5d37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":307,
                  "y":112},
                "size":{
                  "width":80,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设备绑定/u12.png"}},
{
          "id":"12e62fa1e775473d8b3a970866879f34",
          "label":"软键盘",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":368},
            "size":{
              "width":322,
              "height":200}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3eaa54945859465c857e53a444da394b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d8462cd1654d486d944d6224734257fc",
                  "label":"",
                  "parentDynamicPanel":"12e62fa1e775473d8b3a970866879f34",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ce808e57535473bad69b801b86dba54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12e62fa1e775473d8b3a970866879f34",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":200}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设备绑定/u15.png"}}]}]},
{
          "id":"4492c9ed7acf4b92bb8c5dd68a157ea3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":230},
            "size":{
              "width":322,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"289a29c3047b468694d787cb4733da4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":230},
                "size":{
                  "width":322,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u45.png"}},
{
          "id":"f4a66054e1254f85abba4bad541a5357",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":171},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d6ad3f504041a19e29fa77277e15e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":171},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/亲情设备管理/u6.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "ea4f7bb220cd4bbb81ab930bc80242df":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "9906bcc370bf455e91ae86e15ded411d":{
      "scriptId":"u6"},
    "39af8eb78b01490985e6596ea5ba1cdf":{
      "scriptId":"u7"},
    "becddf3ac5994c50afdc664c08ffbbe6":{
      "scriptId":"u8"},
    "7e10ea809c4a4a77adec50997fbf8cec":{
      "scriptId":"u9"},
    "659f2c4a690e48588c338b6afc76cbb7":{
      "scriptId":"u10"},
    "62531fa630fa4b0fb5ebe7a2e4fdc166":{
      "scriptId":"u11"},
    "cb3e98e9f38e466ab3d6e04214c9fe91":{
      "scriptId":"u12"},
    "63e65217bc564b4a94d0da9342be5d37":{
      "scriptId":"u13"},
    "12e62fa1e775473d8b3a970866879f34":{
      "scriptId":"u14"},
    "d8462cd1654d486d944d6224734257fc":{
      "scriptId":"u15"},
    "7ce808e57535473bad69b801b86dba54":{
      "scriptId":"u16"},
    "4492c9ed7acf4b92bb8c5dd68a157ea3":{
      "scriptId":"u17"},
    "289a29c3047b468694d787cb4733da4a":{
      "scriptId":"u18"},
    "f4a66054e1254f85abba4bad541a5357":{
      "scriptId":"u19"},
    "a6d6ad3f504041a19e29fa77277e15e3":{
      "scriptId":"u20"}}});