$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1429966253334.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ef22ff4f784c422086be39e6a1dfb5ce",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f68e8e429914e75bc350352507e7385",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":14}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"1353cdf6e49b49bda9df4589831e67d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":71,
              "y":518},
            "size":{
              "width":321,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e983f34c99249ab9fc23ca631dcd5c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":71,
                  "y":518},
                "size":{
                  "width":321,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"84399aa6ada343a19c6bc8a62c908536",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":529},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80412e10c95c4c82aae04691b87d02ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":529},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"6d62274140874ef39fca1ec7535ef048",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":529},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0103462f054258b24e52b83a5096e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":529},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"2debf30d16304a47922f7a7d26f88938",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":91,
              "y":550},
            "size":{
              "width":29,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba2589601c6d43ca884ff55a0dee1ed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":550},
                "size":{
                  "width":29,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"393b422deec949ac8f9cb60f8537120a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":200,
              "y":549},
            "size":{
              "width":29,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26b662af56304c878d9beabbfddb7f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":549},
                "size":{
                  "width":29,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息",
                      "target":{
                        "targetType":"page",
                        "url":"消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fec5c2363664ac09ac76cf0b3a84703",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":331,
              "y":550},
            "size":{
              "width":29,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87e3702c59a14e88815b5097fbb9b861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":331,
                  "y":550},
                "size":{
                  "width":29,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2679a679af0b431d88f0e403678e682a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":71,
              "y":113},
            "size":{
              "width":321,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09be84a9ed9b49dc824057f59d6e69d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":71,
                  "y":113},
                "size":{
                  "width":321,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 档案管理",
                      "target":{
                        "targetType":"page",
                        "url":"档案管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u18.png"}},
{
          "id":"04beada0a6f94cf887067f2c5682690d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":150},
            "size":{
              "width":321,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f19190614c4acd917d17acdc008ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":150},
                "size":{
                  "width":321,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u20.png"}},
{
          "id":"8ec55da091864a488b592e555386cb7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":160},
            "size":{
              "width":300,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6202ad1625d645dcaf543b91e1227fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":160},
                "size":{
                  "width":300,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"832b4a33fbda4c88bba560b5c025ba78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":250},
            "size":{
              "width":140,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0440b3cc39641e18fceb4ed6c83c032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":250},
                "size":{
                  "width":140,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 档案管理",
                      "target":{
                        "targetType":"page",
                        "url":"档案管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"ee0f4d3a466b48aa9ab4607043b05826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":250},
            "size":{
              "width":160,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d60785b4ae4fe6b2c0e26f7c02645a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":250},
                "size":{
                  "width":160,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 智能呼叫",
                      "target":{
                        "targetType":"page",
                        "url":"智能呼叫.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u26.png"}},
{
          "id":"5880b588de9d4ba485a84a4ec5d17038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":140,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8a93242c764c83b7fcce28665deee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":140,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 定位",
                      "target":{
                        "targetType":"page",
                        "url":"定位.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u28.png"}},
{
          "id":"22a4a4ca8ff34eb68c5a02ebad41f868",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":330},
            "size":{
              "width":160,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c2b54768d44dfbacc592f35bac2201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":330},
                "size":{
                  "width":160,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 视频监控",
                      "target":{
                        "targetType":"page",
                        "url":"视频监控.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u30.png"}},
{
          "id":"bacc647d63914fad828f8e71609279a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":429},
            "size":{
              "width":140,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a0523907948444ab618a960c7d9b068",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":429},
                "size":{
                  "width":140,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 远程远程监护",
                      "target":{
                        "targetType":"page",
                        "url":"远程远程监护.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u32.png"}},
{
          "id":"7d778434566c40e1be1c1d34d31b48be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":429},
            "size":{
              "width":160,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f0f670e63741ed9d797bce1dede849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":429},
                "size":{
                  "width":160,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 一卡通",
                      "target":{
                        "targetType":"page",
                        "url":"一卡通.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u34.png"}},
{
          "id":"a52fe4ef7ba6452ab6f3890565f4c8ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":525},
            "size":{
              "width":25,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5a5065c41d403ea59bb78a8eec2d3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":525},
                "size":{
                  "width":25,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u36.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "2f68e8e429914e75bc350352507e7385":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "1353cdf6e49b49bda9df4589831e67d3":{
      "scriptId":"u6"},
    "3e983f34c99249ab9fc23ca631dcd5c7":{
      "scriptId":"u7"},
    "84399aa6ada343a19c6bc8a62c908536":{
      "scriptId":"u8"},
    "80412e10c95c4c82aae04691b87d02ea":{
      "scriptId":"u9"},
    "6d62274140874ef39fca1ec7535ef048":{
      "scriptId":"u10"},
    "0f0103462f054258b24e52b83a5096e3":{
      "scriptId":"u11"},
    "2debf30d16304a47922f7a7d26f88938":{
      "scriptId":"u12"},
    "ba2589601c6d43ca884ff55a0dee1ed7":{
      "scriptId":"u13"},
    "393b422deec949ac8f9cb60f8537120a":{
      "scriptId":"u14"},
    "26b662af56304c878d9beabbfddb7f99":{
      "scriptId":"u15"},
    "6fec5c2363664ac09ac76cf0b3a84703":{
      "scriptId":"u16"},
    "87e3702c59a14e88815b5097fbb9b861":{
      "scriptId":"u17"},
    "2679a679af0b431d88f0e403678e682a":{
      "scriptId":"u18"},
    "09be84a9ed9b49dc824057f59d6e69d0":{
      "scriptId":"u19"},
    "04beada0a6f94cf887067f2c5682690d":{
      "scriptId":"u20"},
    "b6f19190614c4acd917d17acdc008ae2":{
      "scriptId":"u21"},
    "8ec55da091864a488b592e555386cb7d":{
      "scriptId":"u22"},
    "6202ad1625d645dcaf543b91e1227fda":{
      "scriptId":"u23"},
    "832b4a33fbda4c88bba560b5c025ba78":{
      "scriptId":"u24"},
    "f0440b3cc39641e18fceb4ed6c83c032":{
      "scriptId":"u25"},
    "ee0f4d3a466b48aa9ab4607043b05826":{
      "scriptId":"u26"},
    "23d60785b4ae4fe6b2c0e26f7c02645a":{
      "scriptId":"u27"},
    "5880b588de9d4ba485a84a4ec5d17038":{
      "scriptId":"u28"},
    "ec8a93242c764c83b7fcce28665deee3":{
      "scriptId":"u29"},
    "22a4a4ca8ff34eb68c5a02ebad41f868":{
      "scriptId":"u30"},
    "33c2b54768d44dfbacc592f35bac2201":{
      "scriptId":"u31"},
    "bacc647d63914fad828f8e71609279a7":{
      "scriptId":"u32"},
    "6a0523907948444ab618a960c7d9b068":{
      "scriptId":"u33"},
    "7d778434566c40e1be1c1d34d31b48be":{
      "scriptId":"u34"},
    "57f0f670e63741ed9d797bce1dede849":{
      "scriptId":"u35"},
    "a52fe4ef7ba6452ab6f3890565f4c8ec":{
      "scriptId":"u36"},
    "bb5a5065c41d403ea59bb78a8eec2d3f":{
      "scriptId":"u37"}}});