$axure.loadCurrentPage({
  "url":"账号注册.html",
  "generationDate":new Date(1429966253119.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4da996a9b77f41f9bc0904a52766dd13",
    "type":"Axure:Page",
    "name":"账号注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d86e34428fb43ad8edc0850b2b45b16",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":18}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"cba8142841ef4b8ca8a3c7a9aab36fd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":120},
            "size":{
              "width":322,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"539f9bf7638e4985b075067457b5cc08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":120},
                "size":{
                  "width":322,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号注册/u6.png"}},
{
          "id":"553189733bf245dab62c170616378954",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":74,
              "y":120},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18b6f15e87134b2cad7417c76433c40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":74,
                  "y":120},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号登陆",
                      "target":{
                        "targetType":"page",
                        "url":"账号登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号注册/u8.png"}},
{
          "id":"1c4a7d8afe2a4ba08ae57eea858c464b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":470,
              "y":100},
            "size":{
              "width":300,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78e3bca9ef174acc9ce33101d3726eaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":470,
                  "y":100},
                "size":{
                  "width":300,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号注册/u10.png"}},
{
          "id":"9632cf0571ed493cbdace5adb06d44f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":120},
            "size":{
              "width":322,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd97144dc624ba086ca11a0423f2dd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":120},
                "size":{
                  "width":322,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号注册/u12.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "4d86e34428fb43ad8edc0850b2b45b16":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "cba8142841ef4b8ca8a3c7a9aab36fd5":{
      "scriptId":"u6"},
    "539f9bf7638e4985b075067457b5cc08":{
      "scriptId":"u7"},
    "553189733bf245dab62c170616378954":{
      "scriptId":"u8"},
    "18b6f15e87134b2cad7417c76433c40d":{
      "scriptId":"u9"},
    "1c4a7d8afe2a4ba08ae57eea858c464b":{
      "scriptId":"u10"},
    "78e3bca9ef174acc9ce33101d3726eaa":{
      "scriptId":"u11"},
    "9632cf0571ed493cbdace5adb06d44f0":{
      "scriptId":"u12"},
    "4cd97144dc624ba086ca11a0423f2dd9":{
      "scriptId":"u13"}}});