$axure.loadCurrentPage({
  "url":"定位.html",
  "generationDate":new Date(1429966253680.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"10064f585fe943149e750de84102e94a",
    "type":"Axure:Page",
    "name":"定位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38bea782c0894baa9e630c59abc1df2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":240,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e05beb227014ffa965b30604c422bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":240,
                  "height":477}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u0.png"}},
{
          "id":"12b008a7ebb74caaaabc0a8906442a6e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"b078fd07cb8749ccab4c401990ff15ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f2e572841a7444a9a34bf920d76a3fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"3857782236c04d1f8f1906ba9a8d2134",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":86,
              "y":545},
            "size":{
              "width":57,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"023fe85e3b20487faf43a4f86832816e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":545},
                "size":{
                  "width":57,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee3d68d2529d4ebaaff4283de5e04f75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":190,
              "y":545},
            "size":{
              "width":57,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6109f0e657545d29f41af3b1e78c38c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":545},
                "size":{
                  "width":57,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e16bd72e265d4c629f6d78559fd47528",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":306,
              "y":546},
            "size":{
              "width":57,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8361e38022794d6794a7c051bad825df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":546},
                "size":{
                  "width":57,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"301c4f86606f487abaddb5ef246a10f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":140},
            "size":{
              "width":310,
              "height":385}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873275d501e14820b2e0dc35c00658c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":140},
                "size":{
                  "width":310,
                  "height":385}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u16.jpg"}},
{
          "id":"500bb18a024f4cb38d3acd1a6750841d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":525},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f4132e37e2482797dea7acc7e7e6e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":525},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u18.png"}},
{
          "id":"024684114e8e4a909b8a79ed60640a0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":203.5,
              "y":525},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f766f7bd16e4ed7bd28b5515a44d5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203.5,
                  "y":525},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史回放",
                      "target":{
                        "targetType":"page",
                        "url":"历史回放.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/定位/u18.png"}},
{
          "id":"82518824445e41a6a3050cc2de9f8aad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319.5,
              "y":525},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"190c60a23fe24c36991036f7b9d6d469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319.5,
                  "y":525},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史记录",
                      "target":{
                        "targetType":"page",
                        "url":"历史记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/定位/u18.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "38bea782c0894baa9e630c59abc1df2f":{
      "scriptId":"u0"},
    "9e05beb227014ffa965b30604c422bed":{
      "scriptId":"u1"},
    "12b008a7ebb74caaaabc0a8906442a6e":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "b078fd07cb8749ccab4c401990ff15ba":{
      "scriptId":"u8"},
    "7f2e572841a7444a9a34bf920d76a3fa":{
      "scriptId":"u9"},
    "3857782236c04d1f8f1906ba9a8d2134":{
      "scriptId":"u10"},
    "023fe85e3b20487faf43a4f86832816e":{
      "scriptId":"u11"},
    "ee3d68d2529d4ebaaff4283de5e04f75":{
      "scriptId":"u12"},
    "e6109f0e657545d29f41af3b1e78c38c":{
      "scriptId":"u13"},
    "e16bd72e265d4c629f6d78559fd47528":{
      "scriptId":"u14"},
    "8361e38022794d6794a7c051bad825df":{
      "scriptId":"u15"},
    "301c4f86606f487abaddb5ef246a10f7":{
      "scriptId":"u16"},
    "873275d501e14820b2e0dc35c00658c8":{
      "scriptId":"u17"},
    "500bb18a024f4cb38d3acd1a6750841d":{
      "scriptId":"u18"},
    "67f4132e37e2482797dea7acc7e7e6e4":{
      "scriptId":"u19"},
    "024684114e8e4a909b8a79ed60640a0c":{
      "scriptId":"u20"},
    "1f766f7bd16e4ed7bd28b5515a44d5c0":{
      "scriptId":"u21"},
    "82518824445e41a6a3050cc2de9f8aad":{
      "scriptId":"u22"},
    "190c60a23fe24c36991036f7b9d6d469":{
      "scriptId":"u23"}}});