$axure.loadCurrentPage({
  "url":"密码重设.html",
  "generationDate":new Date(1429966253275.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3bafe66aeee8413da857ac2461443867",
    "type":"Axure:Page",
    "name":"密码重设",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"491843ff0888484e9acfc8219a4247b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"8571fd60478a4999a9d0291e00d7d7b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":322,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a5c8643513b4fa8add1b212be7701ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":322,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码找回",
                      "target":{
                        "targetType":"page",
                        "url":"密码找回.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/密码找回/u6.png"}},
{
          "id":"953afa1d4c7249648e815cc011e79823",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":190},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c83f74ed81e4e37986d0b481f0b8136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":190},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码找回/u8.png"}},
{
          "id":"b34e9739dbab42fb9c1508370dd6cb00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":229},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b8ad6b02544e94abe07824d16d176b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":229},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码找回/u8.png"}},
{
          "id":"6d4c08c2a0e248bc880f1cadb18a3065",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC66},
            "location":{
              "x":110,
              "y":349},
            "size":{
              "width":239,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b72dfdc6e3a4c429847396325d8334a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66},
                "location":{
                  "x":110,
                  "y":349},
                "size":{
                  "width":239,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 密码设置成功",
                      "objectsToFades":[{
                          "objectPath":["0cdd422455344cc5b0786d1b45b39940"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/密码重设/u12.png"}},
{
          "id":"2601764d77e4451994b4d2c502644224",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":111},
            "size":{
              "width":57,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02e09754cec042c494da996e4333f82e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":111},
                "size":{
                  "width":57,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号注册",
                      "target":{
                        "targetType":"page",
                        "url":"账号注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/密码找回/u20.png"}},
{
          "id":"a7c7f66ca36b41b698d54c806991696d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":110,
              "y":160},
            "size":{
              "width":180,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3644dcb414141e8b8bafa347fd65bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":110,
                  "y":160},
                "size":{
                  "width":180,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码重设/u16.png"}},
{
          "id":"35047ed83797420a884216ae0d0f80ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":480,
              "y":90},
            "size":{
              "width":260,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88624c1c196c4ea39faf8dee290f1297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":480,
                  "y":90},
                "size":{
                  "width":260,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码重设/u18.png"}},
{
          "id":"0cdd422455344cc5b0786d1b45b39940",
          "label":"密码设置成功",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":105.5,
              "y":230},
            "size":{
              "width":240,
              "height":130},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b7ab0478553a4313972be6f818cd48fb",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"baa4839992d74b31874c7c2b1ab58919",
                  "label":"",
                  "parentDynamicPanel":"0cdd422455344cc5b0786d1b45b39940",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":240,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"718075e3fda44d3ab6376ed247abb76e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0cdd422455344cc5b0786d1b45b39940",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":240,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 密码设置成功",
                              "objectsToFades":[{
                                  "objectPath":["0cdd422455344cc5b0786d1b45b39940"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/密码重设/u21.png"}}]}]}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "491843ff0888484e9acfc8219a4247b9":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "8571fd60478a4999a9d0291e00d7d7b4":{
      "scriptId":"u6"},
    "9a5c8643513b4fa8add1b212be7701ac":{
      "scriptId":"u7"},
    "953afa1d4c7249648e815cc011e79823":{
      "scriptId":"u8"},
    "1c83f74ed81e4e37986d0b481f0b8136":{
      "scriptId":"u9"},
    "b34e9739dbab42fb9c1508370dd6cb00":{
      "scriptId":"u10"},
    "a8b8ad6b02544e94abe07824d16d176b":{
      "scriptId":"u11"},
    "6d4c08c2a0e248bc880f1cadb18a3065":{
      "scriptId":"u12"},
    "3b72dfdc6e3a4c429847396325d8334a":{
      "scriptId":"u13"},
    "2601764d77e4451994b4d2c502644224":{
      "scriptId":"u14"},
    "02e09754cec042c494da996e4333f82e":{
      "scriptId":"u15"},
    "a7c7f66ca36b41b698d54c806991696d":{
      "scriptId":"u16"},
    "b3644dcb414141e8b8bafa347fd65bf6":{
      "scriptId":"u17"},
    "35047ed83797420a884216ae0d0f80ec":{
      "scriptId":"u18"},
    "88624c1c196c4ea39faf8dee290f1297":{
      "scriptId":"u19"},
    "0cdd422455344cc5b0786d1b45b39940":{
      "scriptId":"u20"},
    "baa4839992d74b31874c7c2b1ab58919":{
      "scriptId":"u21"},
    "718075e3fda44d3ab6376ed247abb76e":{
      "scriptId":"u22"}}});