$axure.loadCurrentPage({
  "url":"求救记录.html",
  "generationDate":new Date(1429966253651.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"71b0ea4fa65e4764821082a435b05c35",
    "type":"Axure:Page",
    "name":"求救记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a763f1f5a13d42a5a86a9ca5fe1888c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":240,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4ed5e83709465789ed6bd7c5f8aa83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":240,
                  "height":477}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u0.png"}},
{
          "id":"d8f1eb35c1254ec39a12f66713f520e9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"f7b6f9572d6d4b949a960dc8b90c51f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc1800028b214a9fa3ea5e6627010849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"44841d737b0940e3a40fc26470a71f95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":180},
            "size":{
              "width":318,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d5f45a7d504b839e6e659ca3a05971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":180},
                "size":{
                  "width":318,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救记录/u10.png"}},
{
          "id":"245be769f17f4182b24d119f4d6d13e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":140},
            "size":{
              "width":318,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"379bb71563ef4684b9e1dd2333c39919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":140},
                "size":{
                  "width":318,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求救记录/u12.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "a763f1f5a13d42a5a86a9ca5fe1888c1":{
      "scriptId":"u0"},
    "6c4ed5e83709465789ed6bd7c5f8aa83":{
      "scriptId":"u1"},
    "d8f1eb35c1254ec39a12f66713f520e9":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "f7b6f9572d6d4b949a960dc8b90c51f9":{
      "scriptId":"u8"},
    "fc1800028b214a9fa3ea5e6627010849":{
      "scriptId":"u9"},
    "44841d737b0940e3a40fc26470a71f95":{
      "scriptId":"u10"},
    "66d5f45a7d504b839e6e659ca3a05971":{
      "scriptId":"u11"},
    "245be769f17f4182b24d119f4d6d13e2":{
      "scriptId":"u12"},
    "379bb71563ef4684b9e1dd2333c39919":{
      "scriptId":"u13"}}});