$axure.loadCurrentPage({
  "url":"历史记录.html",
  "generationDate":new Date(1429966253770.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6fb919e2a2c4b8795c3a95b2565694e",
    "type":"Axure:Page",
    "name":"历史记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3a2f46af0854ec7808502b32b9865b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":240,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a52b8301bb5048e09191262ba1ba1fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":240,
                  "height":477}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u0.png"}},
{
          "id":"a6b51ad8b2514845a47c2582bef1f857",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"72d0c47e6fb04ceeb9b3b8696ed6e08e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8deaf1666e794acaa6dace0dd8160e99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"1ec287adf89a4261a386ee4029331071",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":86,
              "y":545},
            "size":{
              "width":57,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc64d0bbda04d0e8cfe24f0f9d3dd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":545},
                "size":{
                  "width":57,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d85885b58a44219ad0d21078172f89f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":190,
              "y":545},
            "size":{
              "width":57,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a04e7ed79447d2ad46f06641e5be2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":545},
                "size":{
                  "width":57,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d394dc30c1940e08358ee55097c11cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":306,
              "y":546},
            "size":{
              "width":57,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff59bd2ceff4e49b2fdcc19ca688e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":546},
                "size":{
                  "width":57,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4c133ae09474f0f992edd0b3b1f8c6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":525},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96399a002a94489ea8919506d5839cfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":525},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u18.png"}},
{
          "id":"fef60f766a524124b0036c89da26d50f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":525},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5fe17ae412946b0b7f045195ab15f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":525},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u18.png"}},
{
          "id":"fef03638f6264a6f9fc5994495a9a64d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":525},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc9bc8b4e4a437c974277ecae8644e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":525},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u18.png"}},
{
          "id":"10fe1fb17e824f2cae05f249ac133513",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":160},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bea8ada1da24a4fbf9c336ab3b2d10d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":160},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}},
{
          "id":"6af6ef694de144dba069da9a2abd9456",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":200},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28ce55120be74ba88baa1e9684f4b23b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":200},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}},
{
          "id":"ba690ca7baeb402185702d7a9f604c10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":240},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b219c473deb54db09ed8e1e8a0d34807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":240},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}},
{
          "id":"8978b15f841f4c20bb8ed28a9e973442",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":280},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0bd68dc952945d09baae43e0f8428bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":280},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}},
{
          "id":"48449ce842d34a28b48767a182a4d1cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":320},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3deab456d17f42fa83da372d74c1eb98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":320},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}},
{
          "id":"c465568adaf743b7bf4179a3aa12293f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f1089120e12498c9b2f484d8ae2da6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "f3a2f46af0854ec7808502b32b9865b7":{
      "scriptId":"u0"},
    "a52b8301bb5048e09191262ba1ba1fc1":{
      "scriptId":"u1"},
    "a6b51ad8b2514845a47c2582bef1f857":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "72d0c47e6fb04ceeb9b3b8696ed6e08e":{
      "scriptId":"u8"},
    "8deaf1666e794acaa6dace0dd8160e99":{
      "scriptId":"u9"},
    "1ec287adf89a4261a386ee4029331071":{
      "scriptId":"u10"},
    "2fc64d0bbda04d0e8cfe24f0f9d3dd18":{
      "scriptId":"u11"},
    "0d85885b58a44219ad0d21078172f89f":{
      "scriptId":"u12"},
    "12a04e7ed79447d2ad46f06641e5be2f":{
      "scriptId":"u13"},
    "4d394dc30c1940e08358ee55097c11cb":{
      "scriptId":"u14"},
    "dff59bd2ceff4e49b2fdcc19ca688e01":{
      "scriptId":"u15"},
    "d4c133ae09474f0f992edd0b3b1f8c6e":{
      "scriptId":"u16"},
    "96399a002a94489ea8919506d5839cfc":{
      "scriptId":"u17"},
    "fef60f766a524124b0036c89da26d50f":{
      "scriptId":"u18"},
    "d5fe17ae412946b0b7f045195ab15f74":{
      "scriptId":"u19"},
    "fef03638f6264a6f9fc5994495a9a64d":{
      "scriptId":"u20"},
    "bdc9bc8b4e4a437c974277ecae8644e7":{
      "scriptId":"u21"},
    "10fe1fb17e824f2cae05f249ac133513":{
      "scriptId":"u22"},
    "6bea8ada1da24a4fbf9c336ab3b2d10d":{
      "scriptId":"u23"},
    "6af6ef694de144dba069da9a2abd9456":{
      "scriptId":"u24"},
    "28ce55120be74ba88baa1e9684f4b23b":{
      "scriptId":"u25"},
    "ba690ca7baeb402185702d7a9f604c10":{
      "scriptId":"u26"},
    "b219c473deb54db09ed8e1e8a0d34807":{
      "scriptId":"u27"},
    "8978b15f841f4c20bb8ed28a9e973442":{
      "scriptId":"u28"},
    "f0bd68dc952945d09baae43e0f8428bb":{
      "scriptId":"u29"},
    "48449ce842d34a28b48767a182a4d1cf":{
      "scriptId":"u30"},
    "3deab456d17f42fa83da372d74c1eb98":{
      "scriptId":"u31"},
    "c465568adaf743b7bf4179a3aa12293f":{
      "scriptId":"u32"},
    "1f1089120e12498c9b2f484d8ae2da6d":{
      "scriptId":"u33"}}});