$axure.loadCurrentPage({
  "url":"预警设置.html",
  "generationDate":new Date(1429966253947.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"22fd35b3f314465a870f0e495a523cec",
    "type":"Axure:Page",
    "name":"预警设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"40d4c8765aec49bb880cfdb868788397",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":120},
            "size":{
              "width":203,
              "height":217}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949840f4f147458793307deae9b0aada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":120},
                "size":{
                  "width":203,
                  "height":217}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u0.png"}},
{
          "id":"1f2fe974d4384c4ea2fbf61ede8f36f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"e5fa8a2cf67b45deb70f09521d6a3f43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec70f91ce47446fcbd6bf7486eed328c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"1d8b0751c3b84504a2d2ee1e75e8aac3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":524},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f5a4f5545141b8b7fcc561ac7f933b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":524},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"3db8c97940774d20bc28f203d8b69f00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":524},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f12c3b4b006f4b3881e0e9285958c343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":524},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 远程远程监护",
                      "target":{
                        "targetType":"page",
                        "url":"远程远程监护.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"82c42a21b38d4979bfa4bcfa6238a670",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":524},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1040fd2dea2b44ccba0919e5d23784b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":524},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"edb912a7c70a4bb3ae7425d129a63a4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":346,
              "y":524},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a84628aa06254976b9e166af858f5d3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":346,
                  "y":524},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"7a3ccacdad2542b88aa83670e4203766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":86,
              "y":545},
            "size":{
              "width":29,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8b8e4b50774d5482abb5d4af078db3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":545},
                "size":{
                  "width":29,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"511daefaff3f47e280dbb53f457606f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":250,
              "y":545},
            "size":{
              "width":43,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83387cd77f5549f29c65dad6228827df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":545},
                "size":{
                  "width":43,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"577f78d7b4e747fa98b85c2046eb9cd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":169,
              "y":545},
            "size":{
              "width":29,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a4b369ec2245ef91f3d1be9e52506b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":545},
                "size":{
                  "width":29,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e440ef9caed84368a3b912ea5fa2f246",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":326,
              "y":545},
            "size":{
              "width":57,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20d5077e9a8c46f6a6055e4e21348df9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":545},
                "size":{
                  "width":57,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2c415dba2f644ddafae2b5e8709ad98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":150},
            "size":{
              "width":318,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4185bfaab5554e288bd9499b46a949a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":150},
                "size":{
                  "width":318,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u26.png"}},
{
          "id":"7c6d2df15daa4a4d808c0b9d75e62a07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":290,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaedd0e7d60e42e6a0cea9ec65be7f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":290,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u28.png"}},
{
          "id":"2fedc334c7954505919fd88ecf4f0ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":182},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673ff0549bdb461192cd7fb7374ec773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":182},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ba84d1ffac438385a1d100fc236b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":220},
            "size":{
              "width":290,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988cdb0aa74341ed98d1bc31ab327e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":220},
                "size":{
                  "width":290,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u28.png"}},
{
          "id":"e59589d568b74d9fb14766a9b8c621fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":280},
            "size":{
              "width":290,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80667cc0f63a40699253aea497dfddf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":280},
                "size":{
                  "width":290,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u28.png"}},
{
          "id":"edd8c47030d04f16afa2a946d49f6830",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":232},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd8e63ee211f4200a1b2ee16b1d88323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":232},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b45f7713c2904d07926c681771a7dcde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":292},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9a4eb7728041e189452ad57cb9b393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":292},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c6336c83a23442f96264bcc14f7ff58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":110},
            "size":{
              "width":40,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5388a235684d80a644bac526dc8e80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":110},
                "size":{
                  "width":40,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u40.png"}},
{
          "id":"32a05fe297e04a0d975e004c6579495a",
          "label":"自动下载安装包",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":346,
              "y":170},
            "size":{
              "width":474,
              "height":167},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"50e17ed3a9844e5db08737d0d01f9d5c",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"88f7a23cb2e14522a6491ae5bbe49c06",
                  "label":"",
                  "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF3300FF,
                      "opacity":1},
                    "size":{
                      "width":200,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF9900}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5ef0be8a1024f39b5ca0b948895c4e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF3300FF,
                          "opacity":1},
                        "size":{
                          "width":200,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF9900}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/预警设置/u43.png"}},
{
                  "id":"079877d5a9cb421e9bc582e3b9b5d531",
                  "label":"",
                  "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a40a984924c54a9b8aee0db7cac930cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":200,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/预警设置/u45.png"}},
{
                  "id":"b14150802614439e85d8cfca7c1901b5",
                  "label":"",
                  "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":79},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2abbf5bea18a4fa48fe695ffe1454cb8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":200,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/预警设置/u45.png"}},
{
                  "id":"0682a276a29045e48a101db8c7f80b4d",
                  "label":"",
                  "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFFFFF00},
{
                          "color":0xFFFFFF00}]},
                    "location":{
                      "x":0,
                      "y":118},
                    "size":{
                      "width":200,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60806f546ed442b39c50a7f5c0aca255",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFF00},
{
                              "color":0xFFFFFF00}]},
                        "location":{
                          "x":0,
                          "y":118},
                        "size":{
                          "width":200,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 自动下载安装包",
                              "objectsToFades":[{
                                  "objectPath":["32a05fe297e04a0d975e004c6579495a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/预警设置/u49.png"}},
{
                  "id":"2268a2bdd1964858951d7cc3efc2b672",
                  "label":"",
                  "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":169,
                      "y":53},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6096a0cc5f8a4d0b8fba0694b816682f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":169,
                          "y":53},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"fe57d511030f431581d2e5a257d9f740",
                  "label":"",
                  "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":170,
                      "y":90},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c451b108e2c74a42a175f6da21dbe2a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32a05fe297e04a0d975e004c6579495a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":170,
                          "y":90},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]}]}]},
{
          "id":"e83f81086763478fb7709da51ea49c60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":189},
            "size":{
              "width":421,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d5781224174c09bf48dc2b7d4ef9d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":383,
                  "y":189},
                "size":{
                  "width":421,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u55.png"}},
{
          "id":"5f3af9ead11a4615a5945f442408d71e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":200},
            "size":{
              "width":59,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6014b7dbdde4458b9259c94a10935f90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":200},
                "size":{
                  "width":59,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u57.png"}},
{
          "id":"65dc482e690c4b5bbcd9a08913251579",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":252},
            "size":{
              "width":59,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f7bd1858914dbe8ece6ee143277f3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":252},
                "size":{
                  "width":59,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预警设置/u57.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "40d4c8765aec49bb880cfdb868788397":{
      "scriptId":"u0"},
    "949840f4f147458793307deae9b0aada":{
      "scriptId":"u1"},
    "1f2fe974d4384c4ea2fbf61ede8f36f6":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "e5fa8a2cf67b45deb70f09521d6a3f43":{
      "scriptId":"u8"},
    "ec70f91ce47446fcbd6bf7486eed328c":{
      "scriptId":"u9"},
    "1d8b0751c3b84504a2d2ee1e75e8aac3":{
      "scriptId":"u10"},
    "38f5a4f5545141b8b7fcc561ac7f933b":{
      "scriptId":"u11"},
    "3db8c97940774d20bc28f203d8b69f00":{
      "scriptId":"u12"},
    "f12c3b4b006f4b3881e0e9285958c343":{
      "scriptId":"u13"},
    "82c42a21b38d4979bfa4bcfa6238a670":{
      "scriptId":"u14"},
    "1040fd2dea2b44ccba0919e5d23784b4":{
      "scriptId":"u15"},
    "edb912a7c70a4bb3ae7425d129a63a4e":{
      "scriptId":"u16"},
    "a84628aa06254976b9e166af858f5d3a":{
      "scriptId":"u17"},
    "7a3ccacdad2542b88aa83670e4203766":{
      "scriptId":"u18"},
    "ee8b8e4b50774d5482abb5d4af078db3":{
      "scriptId":"u19"},
    "511daefaff3f47e280dbb53f457606f3":{
      "scriptId":"u20"},
    "83387cd77f5549f29c65dad6228827df":{
      "scriptId":"u21"},
    "577f78d7b4e747fa98b85c2046eb9cd0":{
      "scriptId":"u22"},
    "58a4b369ec2245ef91f3d1be9e52506b":{
      "scriptId":"u23"},
    "e440ef9caed84368a3b912ea5fa2f246":{
      "scriptId":"u24"},
    "20d5077e9a8c46f6a6055e4e21348df9":{
      "scriptId":"u25"},
    "e2c415dba2f644ddafae2b5e8709ad98":{
      "scriptId":"u26"},
    "4185bfaab5554e288bd9499b46a949a8":{
      "scriptId":"u27"},
    "7c6d2df15daa4a4d808c0b9d75e62a07":{
      "scriptId":"u28"},
    "eaedd0e7d60e42e6a0cea9ec65be7f38":{
      "scriptId":"u29"},
    "2fedc334c7954505919fd88ecf4f0ae9":{
      "scriptId":"u30"},
    "673ff0549bdb461192cd7fb7374ec773":{
      "scriptId":"u31"},
    "f6ba84d1ffac438385a1d100fc236b2d":{
      "scriptId":"u32"},
    "988cdb0aa74341ed98d1bc31ab327e11":{
      "scriptId":"u33"},
    "e59589d568b74d9fb14766a9b8c621fa":{
      "scriptId":"u34"},
    "80667cc0f63a40699253aea497dfddf7":{
      "scriptId":"u35"},
    "edd8c47030d04f16afa2a946d49f6830":{
      "scriptId":"u36"},
    "bd8e63ee211f4200a1b2ee16b1d88323":{
      "scriptId":"u37"},
    "b45f7713c2904d07926c681771a7dcde":{
      "scriptId":"u38"},
    "0c9a4eb7728041e189452ad57cb9b393":{
      "scriptId":"u39"},
    "7c6336c83a23442f96264bcc14f7ff58":{
      "scriptId":"u40"},
    "be5388a235684d80a644bac526dc8e80":{
      "scriptId":"u41"},
    "32a05fe297e04a0d975e004c6579495a":{
      "scriptId":"u42"},
    "88f7a23cb2e14522a6491ae5bbe49c06":{
      "scriptId":"u43"},
    "c5ef0be8a1024f39b5ca0b948895c4e1":{
      "scriptId":"u44"},
    "079877d5a9cb421e9bc582e3b9b5d531":{
      "scriptId":"u45"},
    "a40a984924c54a9b8aee0db7cac930cc":{
      "scriptId":"u46"},
    "b14150802614439e85d8cfca7c1901b5":{
      "scriptId":"u47"},
    "2abbf5bea18a4fa48fe695ffe1454cb8":{
      "scriptId":"u48"},
    "0682a276a29045e48a101db8c7f80b4d":{
      "scriptId":"u49"},
    "60806f546ed442b39c50a7f5c0aca255":{
      "scriptId":"u50"},
    "2268a2bdd1964858951d7cc3efc2b672":{
      "scriptId":"u51"},
    "6096a0cc5f8a4d0b8fba0694b816682f":{
      "scriptId":"u52"},
    "fe57d511030f431581d2e5a257d9f740":{
      "scriptId":"u53"},
    "c451b108e2c74a42a175f6da21dbe2a7":{
      "scriptId":"u54"},
    "e83f81086763478fb7709da51ea49c60":{
      "scriptId":"u55"},
    "79d5781224174c09bf48dc2b7d4ef9d9":{
      "scriptId":"u56"},
    "5f3af9ead11a4615a5945f442408d71e":{
      "scriptId":"u57"},
    "6014b7dbdde4458b9259c94a10935f90":{
      "scriptId":"u58"},
    "65dc482e690c4b5bbcd9a08913251579":{
      "scriptId":"u59"},
    "16f7bd1858914dbe8ece6ee143277f3c":{
      "scriptId":"u60"}}});