$axure.loadCurrentPage({
  "url":"远程远程监护.html",
  "generationDate":new Date(1429966253826.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e600ce6e55af4ae88a07e2c97a174143",
    "type":"Axure:Page",
    "name":"远程远程监护",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38bea782c0894baa9e630c59abc1df2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":320,
              "height":157}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e05beb227014ffa965b30604c422bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":320,
                  "height":157}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案信息/u8.png"}},
{
          "id":"12b008a7ebb74caaaabc0a8906442a6e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"b078fd07cb8749ccab4c401990ff15ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f2e572841a7444a9a34bf920d76a3fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"5715ee32531e4df99ee6eb7af895884c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":110},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28bd4edac9f643d4b8ca1fca2696dc78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":110},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/远程远程监护/u10.png"}},
{
          "id":"96f9855cbe964a3da6b1f7b7d1aeb107",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":280},
            "size":{
              "width":264,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b0056571cb2457e9b7c16db8fd2688d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":280},
                "size":{
                  "width":264,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u10.png"}},
{
          "id":"a16fc448ddb4453590e238a04650e513",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":340},
            "size":{
              "width":264,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"539c39e9e2bd40068e480dcfc236a84d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":340},
                "size":{
                  "width":264,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u10.png"}},
{
          "id":"56346ec2257448d0bdd9bdeef033989f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":420},
            "size":{
              "width":264,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eac31c291424be282e1dc7c4e17769a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":420},
                "size":{
                  "width":264,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u10.png"}},
{
          "id":"1d6efabbd8194a31b8c9b51310482d0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":150},
            "size":{
              "width":286,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7134be74406e4b0db3b31f1adb91f675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":150},
                "size":{
                  "width":286,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/远程远程监护/u18.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "38bea782c0894baa9e630c59abc1df2f":{
      "scriptId":"u0"},
    "9e05beb227014ffa965b30604c422bed":{
      "scriptId":"u1"},
    "12b008a7ebb74caaaabc0a8906442a6e":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "b078fd07cb8749ccab4c401990ff15ba":{
      "scriptId":"u8"},
    "7f2e572841a7444a9a34bf920d76a3fa":{
      "scriptId":"u9"},
    "5715ee32531e4df99ee6eb7af895884c":{
      "scriptId":"u10"},
    "28bd4edac9f643d4b8ca1fca2696dc78":{
      "scriptId":"u11"},
    "96f9855cbe964a3da6b1f7b7d1aeb107":{
      "scriptId":"u12"},
    "8b0056571cb2457e9b7c16db8fd2688d":{
      "scriptId":"u13"},
    "a16fc448ddb4453590e238a04650e513":{
      "scriptId":"u14"},
    "539c39e9e2bd40068e480dcfc236a84d":{
      "scriptId":"u15"},
    "56346ec2257448d0bdd9bdeef033989f":{
      "scriptId":"u16"},
    "1eac31c291424be282e1dc7c4e17769a":{
      "scriptId":"u17"},
    "1d6efabbd8194a31b8c9b51310482d0c":{
      "scriptId":"u18"},
    "7134be74406e4b0db3b31f1adb91f675":{
      "scriptId":"u19"}}});