$axure.loadCurrentPage({
  "url":"求助.html",
  "generationDate":new Date(1429966253608.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"03447df5da1b48f89b12e17cbfe24c05",
    "type":"Axure:Page",
    "name":"求助",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"76ae6048ae43466e8993271f142580c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":93},
            "size":{
              "width":240,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32c2151f6034e85aa1b54266daadd5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":93},
                "size":{
                  "width":240,
                  "height":477}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/智能呼叫/u0.png"}},
{
          "id":"94f14c7bfc0e49fbbe27f219d75cb75c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"80a4f88e6b014890a96c37b99c93beb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c7427e67c884ff5af5bfe25e5635a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"7b576149a4f748ae9f3b85bc449e9688",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":140},
            "size":{
              "width":318,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"961c052a59de4896922ac393463a2055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":140},
                "size":{
                  "width":318,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求助/u10.jpeg"}},
{
          "id":"887c2f1efdfe4603a53fdabc63e3d473",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":540},
            "size":{
              "width":153,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e93a95a272794da5969c07b44ac1aae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":540},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求助/u12.png"}},
{
          "id":"2c53bba90ca746b89d0e3bdf1b37a429",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":110},
            "size":{
              "width":290,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"535dfc4acb6e4b59a8930c407ec721d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":110},
                "size":{
                  "width":290,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求助/u14.jpeg"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "76ae6048ae43466e8993271f142580c7":{
      "scriptId":"u0"},
    "a32c2151f6034e85aa1b54266daadd5d":{
      "scriptId":"u1"},
    "94f14c7bfc0e49fbbe27f219d75cb75c":{
      "scriptId":"u2",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u3"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u4"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u5"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u6"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u7"}},
    "80a4f88e6b014890a96c37b99c93beb9":{
      "scriptId":"u8"},
    "1c7427e67c884ff5af5bfe25e5635a03":{
      "scriptId":"u9"},
    "7b576149a4f748ae9f3b85bc449e9688":{
      "scriptId":"u10"},
    "961c052a59de4896922ac393463a2055":{
      "scriptId":"u11"},
    "887c2f1efdfe4603a53fdabc63e3d473":{
      "scriptId":"u12"},
    "e93a95a272794da5969c07b44ac1aae1":{
      "scriptId":"u13"},
    "2c53bba90ca746b89d0e3bdf1b37a429":{
      "scriptId":"u14"},
    "535dfc4acb6e4b59a8930c407ec721d8":{
      "scriptId":"u15"}}});