$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1429966254406.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b0791e97f4db4af58841ef2f274aabf3",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"045cd9dbbd4f4e1c9b30ffbf16845ee8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"0eb374e1d999492bbcc79f1147e185cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":74,
              "y":112},
            "size":{
              "width":322,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb52e7f011d4dfab1aa99c5570bd160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":74,
                  "y":112},
                "size":{
                  "width":322,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通用设置",
                      "target":{
                        "targetType":"page",
                        "url":"通用设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u6.png"}},
{
          "id":"5872a94a1cf54b4f8cd0fc193bcda6be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":74,
              "y":145},
            "size":{
              "width":322,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99fabd4efe624cc980ebf08587be96d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":74,
                  "y":145},
                "size":{
                  "width":322,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"776a47cfba8a47dba9f91acb8148a4bc",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":209},
            "size":{
              "width":310,
              "height":161}},
          "adaptiveStyles":{
}},
{
          "id":"4629873b7bbe49e287c88542cc2049d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":389},
            "size":{
              "width":190,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f88dfb390128486686ca9b6a3c2fe7f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":389},
                "size":{
                  "width":190,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u11.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "045cd9dbbd4f4e1c9b30ffbf16845ee8":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "0eb374e1d999492bbcc79f1147e185cb":{
      "scriptId":"u6"},
    "bdb52e7f011d4dfab1aa99c5570bd160":{
      "scriptId":"u7"},
    "5872a94a1cf54b4f8cd0fc193bcda6be":{
      "scriptId":"u8"},
    "99fabd4efe624cc980ebf08587be96d0":{
      "scriptId":"u9"},
    "776a47cfba8a47dba9f91acb8148a4bc":{
      "scriptId":"u10"},
    "4629873b7bbe49e287c88542cc2049d3":{
      "scriptId":"u11"},
    "f88dfb390128486686ca9b6a3c2fe7f2":{
      "scriptId":"u12"}}});