$axure.loadCurrentPage({
  "url":"账号登陆.html",
  "generationDate":new Date(1429966253187.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0ca5313f932f4f91856a46e6f1da067c",
    "type":"Axure:Page",
    "name":"账号登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02e5cf86243845cb99371a7a32ef4c4d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":18}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"8ea3d2b6a6874fcf8001573c75ffc8eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":74,
              "y":120},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4191704424044c90a937883e2c66fb0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":74,
                  "y":120},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号注册/u8.png"}},
{
          "id":"824818fa9b414fa0bd3d63ddbb1ad141",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":159},
            "size":{
              "width":322,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3def51a26b8e43d38c8abbad7db9623f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":159},
                "size":{
                  "width":322,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u8.png"}},
{
          "id":"fbdcf480b04b4d2e9bb113a32fae4daa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":90,
              "y":176},
            "size":{
              "width":290,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1e71a243f024aba829c8580ca70a05a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":176},
                "size":{
                  "width":290,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u10.png"}},
{
          "id":"c87a2c53e5784b06a634759a29c05315",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":90,
              "y":220},
            "size":{
              "width":290,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aaaa3b64d2b4d53b174fdd0a9a39e78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":220},
                "size":{
                  "width":290,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u12.png"}},
{
          "id":"ef5fbb334f1241c796d74c74da289a59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":183},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f4a61770d44ac083dd228454238d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":183},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"ff26e5540f3040468aa9d2483083ab94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":225},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c76156fde5d4629b099e0d8c01dfdc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":225},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"90ac42d87c3a42d6ad31692be7a38a79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFF00},
{
                  "color":0xFFFFFF00}]},
            "location":{
              "x":90,
              "y":270},
            "size":{
              "width":290,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"409fc1ed808740d5ae27c5e6913a0d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFF00},
{
                      "color":0xFFFFFF00}]},
                "location":{
                  "x":90,
                  "y":270},
                "size":{
                  "width":290,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 登陆成功",
                      "objectsToFades":[{
                          "objectPath":["2992037379934d40aafd0dbf2598af40"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u18.png"}},
{
          "id":"260d521d0e654bd09f794b21db387978",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":320},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77bf533f92384e13a1a6c1abe379b7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":320},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码找回",
                      "target":{
                        "targetType":"page",
                        "url":"密码找回.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79f884012cb74976835e728cf3a05986",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFF9900},
{
                  "color":0xFFFF9900},
{
                  "color":0xFFCC3300},
{
                  "color":0xFFCC3300}]},
            "location":{
              "x":280,
              "y":340},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8d93acb1d374affbf6b268394f16b8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFF9900},
{
                      "color":0xFFFF9900},
{
                      "color":0xFFCC3300},
{
                      "color":0xFFCC3300}]},
                "location":{
                  "x":280,
                  "y":340},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号注册",
                      "target":{
                        "targetType":"page",
                        "url":"账号注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账号登陆/u22.png"}},
{
          "id":"2992037379934d40aafd0dbf2598af40",
          "label":"登陆成功",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":135,
              "y":170},
            "size":{
              "width":200,
              "height":110},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"62fe5970240c479e861d52788e073e70",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eaebff8e20544ef4b084dffcff6108b9",
                  "label":"",
                  "parentDynamicPanel":"2992037379934d40aafd0dbf2598af40",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66FF00},
                    "size":{
                      "width":200,
                      "height":110}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c00b0f8c113a4824b8fd4c4db8ea09fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2992037379934d40aafd0dbf2598af40",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66FF00},
                        "size":{
                          "width":200,
                          "height":110}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 登陆成功",
                              "objectsToFades":[{
                                  "objectPath":["2992037379934d40aafd0dbf2598af40"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/账号登陆/u25.png"}}]}]},
{
          "id":"4fa50cd4624143e8afae4d6cd1f59ff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":470,
              "y":97},
            "size":{
              "width":260,
              "height":462}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d03d46c84a24277b8895ba860dbe7a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":470,
                  "y":97},
                "size":{
                  "width":260,
                  "height":462}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u27.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "02e5cf86243845cb99371a7a32ef4c4d":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "8ea3d2b6a6874fcf8001573c75ffc8eb":{
      "scriptId":"u6"},
    "4191704424044c90a937883e2c66fb0a":{
      "scriptId":"u7"},
    "824818fa9b414fa0bd3d63ddbb1ad141":{
      "scriptId":"u8"},
    "3def51a26b8e43d38c8abbad7db9623f":{
      "scriptId":"u9"},
    "fbdcf480b04b4d2e9bb113a32fae4daa":{
      "scriptId":"u10"},
    "a1e71a243f024aba829c8580ca70a05a":{
      "scriptId":"u11"},
    "c87a2c53e5784b06a634759a29c05315":{
      "scriptId":"u12"},
    "0aaaa3b64d2b4d53b174fdd0a9a39e78":{
      "scriptId":"u13"},
    "ef5fbb334f1241c796d74c74da289a59":{
      "scriptId":"u14"},
    "72f4a61770d44ac083dd228454238d98":{
      "scriptId":"u15"},
    "ff26e5540f3040468aa9d2483083ab94":{
      "scriptId":"u16"},
    "5c76156fde5d4629b099e0d8c01dfdc6":{
      "scriptId":"u17"},
    "90ac42d87c3a42d6ad31692be7a38a79":{
      "scriptId":"u18"},
    "409fc1ed808740d5ae27c5e6913a0d46":{
      "scriptId":"u19"},
    "260d521d0e654bd09f794b21db387978":{
      "scriptId":"u20"},
    "77bf533f92384e13a1a6c1abe379b7eb":{
      "scriptId":"u21"},
    "79f884012cb74976835e728cf3a05986":{
      "scriptId":"u22"},
    "f8d93acb1d374affbf6b268394f16b8a":{
      "scriptId":"u23"},
    "2992037379934d40aafd0dbf2598af40":{
      "scriptId":"u24"},
    "eaebff8e20544ef4b084dffcff6108b9":{
      "scriptId":"u25"},
    "c00b0f8c113a4824b8fd4c4db8ea09fe":{
      "scriptId":"u26"},
    "4fa50cd4624143e8afae4d6cd1f59ff6":{
      "scriptId":"u27"},
    "0d03d46c84a24277b8895ba860dbe7a3":{
      "scriptId":"u28"}}});