$axure.loadCurrentPage({
  "url":"消息内容.html",
  "generationDate":new Date(1429966253398.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0a84c223e8d84084a183883359c70fb9",
    "type":"Axure:Page",
    "name":"消息内容",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0aceb2ff10da43b9913d4744ebe3f6f2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"adca9b0bc2fa4bfb9f0c1803a964609d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":65,
              "y":112},
            "size":{
              "width":322,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f96cbf6d974bf7ba54372235713ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":65,
                  "y":112},
                "size":{
                  "width":322,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息",
                      "target":{
                        "targetType":"page",
                        "url":"消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/消息/u6.png"}},
{
          "id":"f87f457c961a460fb31f63344f13056f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCFF},
            "location":{
              "x":65,
              "y":143},
            "size":{
              "width":322,
              "height":426}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b099430bdce4d61a11e2e41e37bbd56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCFF},
                "location":{
                  "x":65,
                  "y":143},
                "size":{
                  "width":322,
                  "height":426}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息内容/u8.png"}},
{
          "id":"ef7800a9e1ed46019e93c48ae83b5c2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":230,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf329254fe04018949a8886eecac534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":230,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息内容/u10.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "0aceb2ff10da43b9913d4744ebe3f6f2":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "adca9b0bc2fa4bfb9f0c1803a964609d":{
      "scriptId":"u6"},
    "38f96cbf6d974bf7ba54372235713ef4":{
      "scriptId":"u7"},
    "f87f457c961a460fb31f63344f13056f":{
      "scriptId":"u8"},
    "6b099430bdce4d61a11e2e41e37bbd56":{
      "scriptId":"u9"},
    "ef7800a9e1ed46019e93c48ae83b5c2c":{
      "scriptId":"u10"},
    "caf329254fe04018949a8886eecac534":{
      "scriptId":"u11"}}});