$axure.loadCurrentPage({
  "url":"密码找回.html",
  "generationDate":new Date(1429966253238.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2a2d3d6181d14c63a1016b01a629f3a7",
    "type":"Axure:Page",
    "name":"密码找回",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4bf757f3be614f0c84dc6552c78ae775",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"7f96041617f54cc0be50956940e39a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":322,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12040965e9c440fab493fec0fd57e9fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":322,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号登陆",
                      "target":{
                        "targetType":"page",
                        "url":"账号登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/密码找回/u6.png"}},
{
          "id":"198fabcae09e475b83d70005a8f16259",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":190},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae450016cda430aa8bee2c2478c70be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":190},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码找回/u8.png"}},
{
          "id":"89646e854bcb4efa859415de8291512f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":200},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d43f75a742fe4ae29314e1cbc2cb076a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":200},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"bc97b0b13e644ee79cd1d08dc4949a5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":229},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52cf772bdd594ef4b4ad61437fbfebdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":229},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码找回/u12.png"}},
{
          "id":"c71f4b73268a441387ebb14f65adc574",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":240},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f3886334f0446f922958060375a189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":240},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号登陆/u14.png"}},
{
          "id":"7ab12ad63f3644f5a531229c372a63a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFCC},
{
                  "color":0xFFFFFFCC},
{
                  "color":0xFFFF6600},
{
                  "color":0xFFFF6600}]},
            "location":{
              "x":249,
              "y":229},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b900b44e644325992591b21d2edd08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFCC},
{
                      "color":0xFFFFFFCC},
{
                      "color":0xFFFF6600},
{
                      "color":0xFFFF6600}]},
                "location":{
                  "x":249,
                  "y":229},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码找回/u16.png"}},
{
          "id":"44106d83047744b58ff30309904f1837",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC66},
            "location":{
              "x":110,
              "y":290},
            "size":{
              "width":239,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4b611a47274598b90dfe6c7da6cf93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66},
                "location":{
                  "x":110,
                  "y":290},
                "size":{
                  "width":239,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码重设",
                      "target":{
                        "targetType":"page",
                        "url":"密码重设.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/密码找回/u18.png"}},
{
          "id":"8bd9a1af484344bb89f2bbd0973f9de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":111},
            "size":{
              "width":57,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"863f7d230d1442a7b217c9d362f24609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":111},
                "size":{
                  "width":57,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号注册",
                      "target":{
                        "targetType":"page",
                        "url":"账号注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/密码找回/u20.png"}},
{
          "id":"300a7008c7184958b4e3c96e61d7681e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":460,
              "y":90},
            "size":{
              "width":260,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"349d58816a5a40728d7acc100b097fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":460,
                  "y":90},
                "size":{
                  "width":260,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码找回/u22.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "4bf757f3be614f0c84dc6552c78ae775":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "7f96041617f54cc0be50956940e39a8c":{
      "scriptId":"u6"},
    "12040965e9c440fab493fec0fd57e9fa":{
      "scriptId":"u7"},
    "198fabcae09e475b83d70005a8f16259":{
      "scriptId":"u8"},
    "4ae450016cda430aa8bee2c2478c70be":{
      "scriptId":"u9"},
    "89646e854bcb4efa859415de8291512f":{
      "scriptId":"u10"},
    "d43f75a742fe4ae29314e1cbc2cb076a":{
      "scriptId":"u11"},
    "bc97b0b13e644ee79cd1d08dc4949a5e":{
      "scriptId":"u12"},
    "52cf772bdd594ef4b4ad61437fbfebdf":{
      "scriptId":"u13"},
    "c71f4b73268a441387ebb14f65adc574":{
      "scriptId":"u14"},
    "d2f3886334f0446f922958060375a189":{
      "scriptId":"u15"},
    "7ab12ad63f3644f5a531229c372a63a3":{
      "scriptId":"u16"},
    "98b900b44e644325992591b21d2edd08":{
      "scriptId":"u17"},
    "44106d83047744b58ff30309904f1837":{
      "scriptId":"u18"},
    "ad4b611a47274598b90dfe6c7da6cf93":{
      "scriptId":"u19"},
    "8bd9a1af484344bb89f2bbd0973f9de5":{
      "scriptId":"u20"},
    "863f7d230d1442a7b217c9d362f24609":{
      "scriptId":"u21"},
    "300a7008c7184958b4e3c96e61d7681e":{
      "scriptId":"u22"},
    "349d58816a5a40728d7acc100b097fb1":{
      "scriptId":"u23"}}});