$axure.loadCurrentPage({
  "url":"健康信息.html",
  "generationDate":new Date(1429966253859.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8574f2a0dfd4ae4ae8bb3e242eb963b",
    "type":"Axure:Page",
    "name":"健康信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1f2fe974d4384c4ea2fbf61ede8f36f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":431,
              "height":652}},
          "adaptiveStyles":{
},
          "masterId":"841c00d307d9455a96e8cb7f2f6f94d4"},
{
          "id":"e5fa8a2cf67b45deb70f09521d6a3f43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1B1B1B,
              "opacity":1},
            "location":{
              "x":65,
              "y":111},
            "size":{
              "width":318,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec70f91ce47446fcbd6bf7486eed328c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":111},
                "size":{
                  "width":318,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案管理/u6.png"}},
{
          "id":"f84a5d9bf04a445bbb85478e2b4799b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":93},
            "size":{
              "width":390,
              "height":157}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d52237ff74fa47119a0c333ef7ff16eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":93},
                "size":{
                  "width":390,
                  "height":157}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康信息/u8.png"}},
{
          "id":"7b8d0cf2e5004781b1d84b1a42640379",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":230,
              "y":117.5},
            "size":{
              "width":15,
              "height":15},
            "rotation":"270",
            "textRotation":"270",
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5e0f7c7e5441bbba788207900206ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":230,
                  "y":117.5},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"270",
                "textRotation":"270",
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康信息/u10.png"}},
{
          "id":"42aca773c91a4f45a2f5eacd79c9910e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":186},
            "size":{
              "width":311,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6821dd3ad5e466b98d089f919c79a64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":186},
                "size":{
                  "width":311,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案信息/u10.png"}},
{
          "id":"34194a6927a34ad49ea4938636eb712f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":410},
            "size":{
              "width":318,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df4d3cf3d444df88d110e0dd860b562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":410},
                "size":{
                  "width":318,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康信息/u14.png"}},
{
          "id":"078449bf8def49f0be0051e70f4b857f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":115},
            "size":{
              "width":50,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de26e351ec424f8d8ca08ee25e189a93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":115},
                "size":{
                  "width":50,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康信息/u16.png"}},
{
          "id":"a794847a24e24675a1ad659553857bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":150},
            "size":{
              "width":280,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f5defa3e811463abcb80a7545f0334a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":150},
                "size":{
                  "width":280,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康信息/u18.png"}},
{
          "id":"4a08aa9041d6494fa59a11c9f8696bbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":400},
            "size":{
              "width":56,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65391b1081bf4f8b92e777aa66c729ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":196,
                  "y":400},
                "size":{
                  "width":56,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康信息/u20.png"}}]}},
  "masters":{
    "841c00d307d9455a96e8cb7f2f6f94d4":{
      "packageId":"841c00d307d9455a96e8cb7f2f6f94d4",
      "type":"Axure:Master",
      "name":"安卓外壳修",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3f912b2acbb04cce9ce2e4b71f03a88a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":431,
                "height":652},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d26c95232b849beaba6fb23fac32bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":431,
                    "height":652},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u1.png"}},
{
            "id":"beba3e223a5343ffbf22fc2f7590caa5",
            "label":"",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
}},
{
            "id":"398eaeec54e44cf59c3160d57a94b04d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":76},
              "size":{
                "width":321,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c23f5e734e146aab726fe7c2af2c315",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":76},
                  "size":{
                    "width":321,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端闪屏/u4.png"}}]}}},
  "objectPaths":{
    "1f2fe974d4384c4ea2fbf61ede8f36f6":{
      "scriptId":"u0",
      "3f912b2acbb04cce9ce2e4b71f03a88a":{
        "scriptId":"u1"},
      "8d26c95232b849beaba6fb23fac32bd8":{
        "scriptId":"u2"},
      "beba3e223a5343ffbf22fc2f7590caa5":{
        "scriptId":"u3"},
      "398eaeec54e44cf59c3160d57a94b04d":{
        "scriptId":"u4"},
      "7c23f5e734e146aab726fe7c2af2c315":{
        "scriptId":"u5"}},
    "e5fa8a2cf67b45deb70f09521d6a3f43":{
      "scriptId":"u6"},
    "ec70f91ce47446fcbd6bf7486eed328c":{
      "scriptId":"u7"},
    "f84a5d9bf04a445bbb85478e2b4799b7":{
      "scriptId":"u8"},
    "d52237ff74fa47119a0c333ef7ff16eb":{
      "scriptId":"u9"},
    "7b8d0cf2e5004781b1d84b1a42640379":{
      "scriptId":"u10"},
    "6f5e0f7c7e5441bbba788207900206ba":{
      "scriptId":"u11"},
    "42aca773c91a4f45a2f5eacd79c9910e":{
      "scriptId":"u12"},
    "f6821dd3ad5e466b98d089f919c79a64":{
      "scriptId":"u13"},
    "34194a6927a34ad49ea4938636eb712f":{
      "scriptId":"u14"},
    "7df4d3cf3d444df88d110e0dd860b562":{
      "scriptId":"u15"},
    "078449bf8def49f0be0051e70f4b857f":{
      "scriptId":"u16"},
    "de26e351ec424f8d8ca08ee25e189a93":{
      "scriptId":"u17"},
    "a794847a24e24675a1ad659553857bb4":{
      "scriptId":"u18"},
    "5f5defa3e811463abcb80a7545f0334a":{
      "scriptId":"u19"},
    "4a08aa9041d6494fa59a11c9f8696bbe":{
      "scriptId":"u20"},
    "65391b1081bf4f8b92e777aa66c729ea":{
      "scriptId":"u21"}}});